services:
  web:
    build: .
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/healthcarer?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=healthcarer
    volumes:
      - ./mysql:/var/lib/mysql


